- name: install php
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php
    - php-bcmath
    - php-devel
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pear
    - pcre-devel
    - php-phpunit-PHPUnit
    - php-pecl-xdebug

- name: copy php.ini
  copy:
    src: php.ini
    dest: /etc/php.ini
